[project]
name = "nice_glfw"
version = "1.0.0"
authors = ["Corey Richardson <corey@octayn.net>"]

[dependencies.glfw]

git = "https://github.com/bjz/glfw-rs"

[dependencies.libglfw]

git = "https://github.com/csherratt/glfw"
