[project]

name = "simple"
version = "0.0.1"
authors = ["Corey Richardson <corey@octayn.net>"]

[dependencies.glfw]

git = "https://github.com/bjz/glfw-rs"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs"

[dependencies.nice_glfw]

path = "../../"
